import Head from 'next/head'
import { ContentContainer, Navigation } from '@/components/ui/'
import { PageContainer } from '@/components/ui/page-container'
import { StepsContainer } from '@/components/ui/steps-container'
import { ProgressBox } from '@/components/progress-box'
import {
  StepOne,
  StepTwo,
  StepThree,
  StepFour,
  StepFinal,
} from '../components/steps'
import { NumberContextType } from '@/context/StepNumberProvider'
import { useStepNumber } from '@/hooks/useStepNumber'

function stepContent(step: NumberContextType) {
  switch (step) {
    case 1:
      return <StepOne />
    case 2:
      return <StepTwo />
    case 3:
      return <StepThree />
    case 4:
      return <StepFour />
    case 5:
      return <StepFinal />
    default:
      return <StepOne />
  }
}

export default function Home() {
  const { stepNumber } = useStepNumber()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContainer>
        <ContentContainer>
          <ProgressBox />
          <StepsContainer>
            <div>{stepContent(stepNumber)}</div>
            {stepNumber < 5 && <Navigation />}
          </StepsContainer>
        </ContentContainer>
      </PageContainer>
    </>
  )
}
